spring:
  application:
    name: feedback-service
  profiles:
    active: dev

logging:
  level:
    org.springframework.security.web.FilterChainProxy: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: health, info, prometheus
  prometheus:
    metrics:
      export:
        enabled: true